openapi: 3.0.3
info:
  title: Sets API Changes
  version: 1.0.0
  description: Changes to existing Sets API for word references

paths:
  /api/sets:
    post:
      summary: Create a new set (MODIFIED)
      operationId: createSet
      tags:
        - Sets
      security:
        - bearerAuth: []
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSetRequest'
      responses:
        '201':
          description: Set created
          headers:
            Location:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateSetResponse'
        '400':
          description: Validation error
        '401':
          description: Unauthorized

  /api/sets/{setId}:
    get:
      summary: Get a specific set (MODIFIED response)
      operationId: getSet
      tags:
        - Sets
      security:
        - bearerAuth: []
        - apiKeyAuth: []
      parameters:
        - name: setId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Set details with words
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSetResponse'
        '401':
          description: Unauthorized
        '404':
          description: Set not found

    put:
      summary: Update an existing set (MODIFIED)
      operationId: updateSet
      tags:
        - Sets
      security:
        - bearerAuth: []
        - apiKeyAuth: []
      parameters:
        - name: setId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSetRequest'
      responses:
        '204':
          description: Set updated
        '400':
          description: Validation error
        '401':
          description: Unauthorized
        '404':
          description: Set not found

components:
  schemas:
    CreateSetRequest:
      type: object
      required:
        - setName
        - wordIds
      properties:
        setName:
          type: string
          minLength: 1
          maxLength: 200
        wordIds:
          type: array
          description: Ordered list of word IDs to include in the set
          items:
            type: string
            format: uuid

    CreateSetResponse:
      type: object
      properties:
        setId:
          type: string
          format: uuid

    UpdateSetRequest:
      type: object
      required:
        - setName
        - wordIds
      properties:
        setName:
          type: string
          minLength: 1
          maxLength: 200
        wordIds:
          type: array
          description: Ordered list of word IDs to include in the set
          items:
            type: string
            format: uuid

    GetSetResponse:
      type: object
      properties:
        setId:
          type: string
          format: uuid
        name:
          type: string
        createdAt:
          type: string
          format: date-time
        words:
          type: array
          description: Words in order
          items:
            $ref: '#/components/schemas/WordInSetDto'

    WordInSetDto:
      type: object
      description: Word details when retrieved as part of a set
      properties:
        wordId:
          type: string
          format: uuid
        word:
          type: string
        wordType:
          type: string
        translations:
          type: array
          items:
            type: string
        exampleSentences:
          type: array
          items:
            type: string
