openapi: 3.0.3
info:
  title: Words API
  version: 1.0.0
  description: API endpoints for independent word management

paths:
  /api/words:
    get:
      summary: List words with pagination, sorting, and search
      operationId: getWords
      tags:
        - Words
      security:
        - bearerAuth: []
        - apiKeyAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: pageSize
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 200
            default: 25
        - name: sortingFieldName
          in: query
          schema:
            type: string
            enum: [wordId, word, wordType, createdAt, editedAt]
            default: createdAt
        - name: sortingOrder
          in: query
          schema:
            type: string
            enum: [asc, desc]
            default: desc
        - name: searchQuery
          in: query
          schema:
            type: string
      responses:
        '200':
          description: List of words
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WordsListResponse'
        '401':
          description: Unauthorized

    post:
      summary: Create a new word
      operationId: createWord
      tags:
        - Words
      security:
        - bearerAuth: []
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWordRequest'
      responses:
        '201':
          description: Word created
          headers:
            Location:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateWordResponse'
        '400':
          description: Validation error
        '401':
          description: Unauthorized
        '409':
          description: Word already exists with same type

  /api/words/{wordId}:
    get:
      summary: Get a specific word
      operationId: getWord
      tags:
        - Words
      security:
        - bearerAuth: []
        - apiKeyAuth: []
      parameters:
        - name: wordId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Word details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetWordResponse'
        '401':
          description: Unauthorized
        '404':
          description: Word not found

    put:
      summary: Update an existing word
      operationId: updateWord
      tags:
        - Words
      security:
        - bearerAuth: []
        - apiKeyAuth: []
      parameters:
        - name: wordId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateWordRequest'
      responses:
        '204':
          description: Word updated
        '400':
          description: Validation error
        '401':
          description: Unauthorized
        '404':
          description: Word not found
        '409':
          description: Word already exists with same type

    delete:
      summary: Delete a word
      operationId: deleteWord
      tags:
        - Words
      security:
        - bearerAuth: []
        - apiKeyAuth: []
      parameters:
        - name: wordId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Word deleted
        '401':
          description: Unauthorized

  /api/words/{wordId}/sets:
    get:
      summary: Get sets containing this word
      operationId: getWordSets
      tags:
        - Words
      security:
        - bearerAuth: []
        - apiKeyAuth: []
      parameters:
        - name: wordId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: List of sets containing this word
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WordSetsResponse'
        '401':
          description: Unauthorized
        '404':
          description: Word not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-Api-Key

  schemas:
    WordRecordDto:
      type: object
      properties:
        wordId:
          type: string
          format: uuid
        word:
          type: string
        wordType:
          type: string
        createdAt:
          type: string
          format: date-time
        editedAt:
          type: string
          format: date-time
          nullable: true

    WordsListResponse:
      type: object
      properties:
        count:
          type: integer
        data:
          type: array
          items:
            $ref: '#/components/schemas/WordRecordDto'

    GetWordResponse:
      type: object
      properties:
        wordId:
          type: string
          format: uuid
        word:
          type: string
        wordType:
          type: string
        translations:
          type: array
          items:
            type: string
        exampleSentences:
          type: array
          items:
            type: string
        createdAt:
          type: string
          format: date-time
        editedAt:
          type: string
          format: date-time
          nullable: true

    CreateWordRequest:
      type: object
      required:
        - word
        - wordType
        - translations
      properties:
        word:
          type: string
          minLength: 1
          maxLength: 200
        wordType:
          type: string
          enum: [none, noun, verb, adjective, adverb, other]
        translations:
          type: array
          minItems: 1
          items:
            type: string
            minLength: 1
            maxLength: 200
        exampleSentences:
          type: array
          items:
            type: string
            minLength: 1
            maxLength: 500

    CreateWordResponse:
      type: object
      properties:
        wordId:
          type: string
          format: uuid

    UpdateWordRequest:
      type: object
      required:
        - word
        - wordType
        - translations
      properties:
        word:
          type: string
          minLength: 1
          maxLength: 200
        wordType:
          type: string
          enum: [none, noun, verb, adjective, adverb, other]
        translations:
          type: array
          minItems: 1
          items:
            type: string
            minLength: 1
            maxLength: 200
        exampleSentences:
          type: array
          items:
            type: string
            minLength: 1
            maxLength: 500

    WordSetsResponse:
      type: object
      properties:
        sets:
          type: array
          items:
            type: object
            properties:
              setId:
                type: string
                format: uuid
              name:
                type: string
