<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Scrutor" />
    <PackageReference Include="System.Linq.Dynamic.Core" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="LexicaNext.CLI" />
  </ItemGroup>

</Project>
