name: Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  SQL_MIGRATION_IMAGE_NAME: lrydzkowski/lexica-next-sql-migration
  APP_IMAGE_NAME: lrydzkowski/lexica-next

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Generate version tag
        run: echo "VERSION_TAG=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Show the version tag
        run: echo ${{ env.VERSION_TAG }}

      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install API dependencies
        run: dotnet restore

      - name: Build API
        run: dotnet build --configuration Release --no-restore

      - name: Run API tests
        run: dotnet test --no-restore --verbosity normal

      - name: Sign in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build SQL migration docker image
        id: docker_sql_migration_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./LexicaNext.WebApp/DockerfileSqlMigration
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.SQL_MIGRATION_IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.SQL_MIGRATION_IMAGE_NAME }}:${{ env.VERSION_TAG }}

      - name: Build APP docker image
        id: docker_api_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./LexicaNext.WebApp/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.APP_IMAGE_NAME }}:${{ env.VERSION_TAG }}

      - name: Set tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{ env.VERSION_TAG }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""

    outputs:
      version_tag: ${{ env.VERSION_TAG }}

  deploy:
    runs-on: ubuntu-latest

    needs: build

    environment:
      name: 'dev'

    steps:
      - name: Echo version tag
        run: echo ${{ needs.build.outputs.version_tag }}

      - name: Execute SQL migration
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://r-systems-cloud.com/api/hooks/lexica-next-sql-migration'
          method: 'GET'
          customHeaders: '{"x-api-key": "${{ secrets.DEPLOY_APP_KEY }}"}'
          timeout: 300000

      - name: Deploy APP
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://r-systems-cloud.com/api/hooks/lexica-next'
          method: 'GET'
          customHeaders: '{"x-api-key": "${{ secrets.DEPLOY_APP_KEY }}"}'
          timeout: 300000
